
[creativeModeTabs]
	enableCreativeModeTabs = true
	syncSelectedCreativeModeTab = true
	disabledCreativeModeTabs = ["minecraft:op_blocks"]
	enableBerryTheme = false

[stackGroups]
	enableStackGroups = true

