
#Bird Nest Settings
[general]
	#[range: 0 ~ 1000, default: 40]
	#Range: 0 ~ 1000
	NEST_DROP_RARITY = 10
	#Allows to enable/disable nests stacking [default: false]
	ALLOW_STACKING = true
	#This makes nests more (or less) rare from decaying leaves. Leave at 1 for no change. [range: 0.0 ~ 1000.0, default: 1.25]
	#Range: 0.0 ~ 1000.0
	NEST_DECAY_DROP_MULTIPLIER = 1.25
	#Allows to enable/disable nests dropping from decaying leaves [default: true]
	ALLOW_DECAY_DROPS = false
	#Loot entries for bird nests. Format: item_id, count, chance
	nest_loot_entries = ["minecraft:stick, 1-4, 1.0", "minecraft:feather, 0-3, 1.0", "minecraft:egg, 1, 0.33", "minecraft:string, 1-2, 0.50", "minecraft:bone, 1-2, 0.37", "minecraft:flint, 1, 0.25", "minecraft:wheat_seeds, 1-2, 0.125", "minecraft:melon_seeds, 1, 0.04", "minecraft:pumpkin_seeds, 1, 0.04", "minecraft:beetroot_seeds, 1, 0.04", "minecraft:prismarine_shard, 1, 0.016667", "minecraft:tropical_fish, 1, 0.05", "minecraft:salmon, 1, 0.05", "minecraft:pufferfish, 1, 0.05", "minecraft:cod, 1, 0.05", "minecraft:blaze_powder, 1-2, 0.025"]

