
["Configs for Buildify Mod"]
	#Use Custom Creative Inventory Tabs?
	use_custom_creative_tabs = true
	#Remove all Vanilla Tabs?
	remove_vanilla_tabs = true
	#Use Vanilla Block Families? (This adds doors, signs, etc to Block Picker)
	#If using Buildify without CaliberMod installed, set this to True
	use_vanilla_block_families = false
	#Disable all added OP Commands?
	disable_all_added_op_commands = false
	#Enable Server Logging for Commands?
	command_server_logging = true

