
#Inventory GUI Settings
[inventory]
	#Range: 0 ~ 255
	red = 139
	#Range: 0 ~ 255
	green = 139
	#Range: 0 ~ 255
	blue = 139
	#Range: 0 ~ 255
	alpha = 180

#Chest GUI Settings
[chest]
	#Range: 0 ~ 255
	red = 60
	#Range: 0 ~ 255
	green = 40
	#Range: 0 ~ 255
	blue = 20
	#Range: 0 ~ 255
	alpha = 200

