
[crates]
	#Should the crate HUD render
	show_crate_hud = true
	#Crate HUD horizontal screen alignment (0: left, 1: right)
	#Range: 0.0 ~ 1.0
	crate_hud_x_alignment = 0.0
	#Crate HUD horizontal pixel offset
	#Range: -100 ~ 100
	crate_hud_x_offset = 1
	#Crate HUD vertical screen alignment (0: top, 1: bottom)
	#Range: 0.0 ~ 1.0
	crate_hud_y_alignment = 1.0
	#Crate HUD vertical pixel offset
	#Range: -100 ~ 100
	crate_hud_y_offset = -1
	#Render crate contents instead of crate in first person hand when crate would place contained block
	render_crate_contents_in_hand = true

