
#Golem Stats
[diamethyst_golem_stats]
	#Max health [default:250.0]
	#Range: 0.0 ~ 3000.0
	diamethystGolemMaxHealth = 250.0
	#Movement speed [default:0.375]
	#Range: 0.0 ~ 1.0
	diamethystGolemMovementSpeed = 0.375
	#Attack damage [default:30.0]
	#Range: 0.0 ~ 100.0
	diamethystGolemKnockbackResistance = 30.0
	#Friendly to creator [default: true]
	diamethystGolemFriendly = true

