
#Blacklist blocks from being applied with emitters
#    EXAMPLE: light_blacklist = [
#        "minecraft:torch",			COMMENT: a simple block_id for a torch. It's blacklisted
#        "minecraft:.*torch",		COMMENT: this is a regex, soul_torch, soul_wall_torch, torch, wall_torch from Minecraft's are blacklisted.
#        "minecraft:.*",				COMMENT: This is a regex, all of blocks from Minecraft's are blacklisted.
#        ".*:.*torch"				COMMENT: this is a regex: soul_torch, soul_wall_torch, dim_redstone_torch, and other torches from multiple mods are blacklisted.
#    ]
#
[light_blacklist]
	light_blacklist = []

[glass_blacklist]
	glass_blacklist = []

