
[NbtTooltip]
	#Windows style scroll (scroll down to go down) or Mac style scroll (scroll up to go down)
	WIDOWS_SCROLL = true
	#Maximum number of lines of NBT before we need to scroll.
	#Minimum value: '8'
	SCROLL_IF_MORE_LINES = 16
	#Add a tooltip to view NBT on items when in extra info mode (F3 + H)
	ADD_NBT_TOOLTIP = true

[Log]
	#send the debug calls through the Info log instead of Debug log
	DEBUG_AS_INFO = true
	#do debug calls actually log something. set to false to silence all debug calls
	DO_DEBUG = true

