#This file stores configuration options for Iris, such as the currently active shaderpack
#Mon Apr 27 04:53:32 CDT 2026
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
maxShadowRenderDistance=0
shaderPack=MakeUpUltraFast-master.zip
enableShaders=true
