# Thingamajigs Client Config
# These settings affect the client.
# Be careful to read each config option carefully.
# Textured Creative Tabs
# Enables or disables the creative custom tabs and bg (default: false) NOT WORKING
# Note: this feature makes the Thingamajigs creative tab look like other vanilla tabs, and requires a restart
blueTabs = false
# Config Screen X Offset
# The x offset of the custom config screen (default is -75)
# DO NOT CHANGE IF YOU DON'T KNOW WHAT YOU ARE DOING!
#Range: -300 ~ 300
configOffsetX = -75
# Config Screen Y Offset
# The y offset of the custom config screen (default is -110)
# DO NOT CHANGE IF YOU DON'T KNOW WHAT YOU ARE DOING!
#Range: -300 ~ 300
configOffsetY = -110

