
[AutoMove]
	#Auto move uncrafted items to player inventory, drops to world if inventory is full.
	autoMoveToInventory = true

[StatusColor]
	#Overlay color for No Recipe Found
	#Range: > -2147483648
	noRecipeFound = -40612
	#Overlay color for No Suitable Output Slot
	#Range: > -2147483648
	noSuitableOutputSlotColor = -226487
	#Overlay color for Not Enough Exp
	#Range: > -2147483648
	notEnoughExpColor = -852102
	#Overlay color for Not Enough Input Item
	#Range: > -2147483648
	notEnoughInputItemColor = -4288
	#Overlay color for Not Empty Shulker
	#Range: > -2147483648
	notEmptyShulkerColor = -1799425
	#Overlay color for Restricted By Config
	#Range: > -2147483648
	restrictedByConfigColor = -11579569
	#Overlay color for Damaged Item
	#Range: > -2147483648
	damagedItemColor = -40612
	#Overlay color for Enchanted Item
	#Range: > -2147483648
	enchantedItemColor = -40612
	#Overlay color for Locked Item
	#Range: > -2147483648
	lockedItemColor = -40612
	#Overlay color for Progression Not Defined
	#Range: > -2147483648
	progressionNotDefinedColor = -40612

