#Chance of tendons to spawn.
#Range: 10 ~ 100
tendonChance = 75
#Chance of hanging flesh columns to spawn on tendons.
#Range: 10 ~ 100
columnChance = 50
#Minimum distance since last one before spawning a flesh ball.
#Range: 1 ~ 128
ballOffsetMin = 16
#Maximum distance since last one before spawning a flesh ball.
#Range: 1 ~ 128
ballOffsetMax = 64

[Generation]
	#Minimum horizontal distance the tendon must curve.
	#Lower = Less chance of curve, Higher = More chance of curve
	#Range: 4 ~ 16
	distanceMin = 12
	#Maximum horizontal distance the tendon can curve.
	#Lower = Less chance of curve, Higher = More chance of curve
	#Range: 32 ~ 64
	distanceMax = 32
	#Controls the middle control point of the curve.
	#Lower = More sag, Higher = Less sag
	#Range: 0.1 ~ 0.9
	midPosMultiplier = 0.7
	#Density/spacing of blocks along the curve.
	#Lower = Slower but less chance of skipping blocks, Higher = Faster but more chance of skipping blocks
	#Range: 0.001 ~ 0.01
	stepRate = 0.0035

